package com.liuyf.demos.mybatis;

import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.List;

import org.apache.ibatis.io.Resources;
import org.apache.ibatis.session.SqlSession;
import org.apache.ibatis.session.SqlSessionFactory;
import org.apache.ibatis.session.SqlSessionFactoryBuilder;

import com.liuyf.demos.mybatis.mapper.PersonMapper;
import com.liuyf.demos.mybatis.pojos.Person;

public class MyBatisKickOff {

	public static void main(String[] args) throws IOException, SQLException {
		
		String resource = "mybatis-config.xml";
		InputStream in = Resources.getResourceAsStream(resource);
		SqlSessionFactory factory = new SqlSessionFactoryBuilder().build(in);
		
		SqlSession session = factory.openSession();
		Connection conn = session.getConnection();
		
		try {
			setUp(conn);
			PersonMapper mapper = session.getMapper(PersonMapper.class);
			Person person = new Person();
			person.setName("Tony Liu");
			person.setAddress("SAN YUAN QIAO");
			
			Long id = mapper.save(person);
			
			// full person
			Person fullPerson = mapper.findById(id);
			System.out.println(fullPerson.getName() + " ===>>> " + fullPerson.getAddress());
			
			// only concerned about the basic information
			List<Person> personBasicList = mapper.query(id);
			for (Person p : personBasicList) {
				System.out.println(p.getName() + " ===>>> " + p.getAddress());
			}
		} finally {
			tearDown(conn);
			session.close();
		}
	}

	private static void tearDown(Connection conn) throws SQLException {
		String sql = "drop table tb_person";
		PreparedStatement ps = conn.prepareStatement(sql);
		ps.executeUpdate();
	}

	private static void setUp(Connection conn) throws SQLException {
		String sql = "create table tb_person"
				+ " (id bigint generated by default as identity (start with 1), name varchar(255), address varchar(255),"
				+ " primary key (id))";
		PreparedStatement ps = conn.prepareStatement(sql);
		ps.executeUpdate();
		ps.close();
	}
}
